const sampleSearchHistory = [
  "bridal makeup",
  "party makeup",
  "smokey eye look",
  "glitter makeup",
  "natural makeup look",
  "HD makeup",
  "airbrush makeup",
  "reception makeup",
  "festival makeup",
  "evening glam",
  "dewy skin look",
  "matte finish foundation",
  "bold lip makeup",
  "subtle eye makeup",
  "makeup for photoshoot",
  "daytime makeup",
  "prom makeup",
  "contouring and highlighting",
  "long-lasting makeup",
  "waterproof eyeliner",
  "bridal nail design",
  "french tip nails",
  "glitter nail art",
  "3D nail designs",
  "ombre nails",
  "gel nails",
  "nail extensions",
  "chrome nails",
  "matte nails",
  "minimalist nail design",
  "coffin nail shape",
  "wedding nails",
  "pastel nail colors",
  "valentine’s day nails",
  "floral nail art",
  "bridal beauty package",
  "hair and makeup combo",
  "eye makeup tutorial",
  "eyebrow shaping",
  "eyelash extensions",
  "makeup artist near me",
  "beauty studio home service",
  "nude lipstick shades",
  "nail art for short nails",
  "studio makeup service",
  "celebrity makeup look",
  "makeup for oily skin",
  "smudge-proof kajal",
  "beauty services at home",
  "contour makeup tips",
  "highlighting techniques",
  "wedding makeup trends",
  "festive eye looks",
  "matte lipstick colors",
  "natural bridal look",
  "bold eye makeup ideas",
  "classic red lip",
  "summer makeup ideas",
  "winter skincare makeup",
  "bridal hair styling",
  "ombre hair color",
  "hair and makeup artists",
  "celebrity nail trends",
  "glossy lip makeup",
  "cat eye eyeliner tutorial",
  "foundation matching tips",
  "suitable makeup for glasses",
  "makeup brushes essentials",
  "eyeliner styles",
  "fake eyelash application",
  "bridal mehndi designs",
  "nail care tips",
  "gel vs acrylic nails",
  "nail salon near me",
  "nail polish brands",
  "nail art tools",
  "DIY nail art",
  "manicure and pedicure",
  "kids nail art designs",
  "festive nail designs",
  "minimalist makeup ideas",
  "smokey eye for beginners",
  "bold lipstick shades",
  "bronzer application",
  "eyebrow shaping tools",
  "makeup removal tips",
  "sensitive skin makeup",
  "bridal makeup package prices",
  "wedding makeup checklist",
  "bridal grooming tips",
  "long lasting foundation",
  "how to apply fake lashes",
  "bridal eye makeup step by step",
  "makeup contouring kit",
  "makeup for round face",
  "makeup for oval face",
  "makeup for square face",
  "makeup for hooded eyes",
  "smokey eye makeup step by step",
  "matte vs dewy finish",
  "lipstick application tips",
  "best setting sprays",
  "makeup for mature skin",
  "bridal lipsticks",
  "makeup for daytime events",
  "night party makeup looks",
  "festival makeup ideas",
  "bridal makeup colors",
  "makeup trends 2025",
  "makeup tutorials youtube",
  "natural eyebrow tutorial",
  "how to fill eyebrows",
  "eyebrow threading near me",
  "best eyebrow pencils",
  "beauty salons with makeup service",
  "eyebrow tinting",
  "eyelash perm",
  "beauty salons open late",
  "nail art for beginners",
  "nail art stickers",
  "nail art trends 2025",
  "gel nail removal",
  "acrylic nail removal",
  "nail extension care",
  "nail polish remover",
  "best nail salons",
  "nail art brushes",
  "nail art glitter",
  "bridal hair accessories",
  "bridal jewelry",
  "bridal skincare routine",
  "pre-wedding facial",
  "bridal spa packages",
  "bridal makeup trial",
  "bridal makeup tips",
  "bridal mehndi artists",
  "bridal hair makeup packages",
  "makeup for engagement",
  "bridal makeup ideas for dark skin",
  "bridal makeup ideas for fair skin",
  "bridal makeup for summer weddings",
  "bridal makeup for winter weddings",
  "bridal makeup budget",
  "budget party makeup",
  "budget nail art",
  "bridal hair updos",
  "bridal hair curls",
  "bridal hairstyles for long hair",
  "bridal hairstyles for short hair",
  "bridal hairstyle ideas",
  "wedding guest makeup",
  "wedding guest nail art",
  "party guest makeup ideas",
  "prom makeup ideas",
  "makeup remover wipes",
  "best face primers",
  "makeup setting powders",
  "waterproof mascara",
  "makeup for sensitive eyes",
  "natural makeup for office",
  "day makeup for school",
  "festival makeup colors",
  "bold makeup for festivals",
  "holiday makeup looks",
  "glam makeup tutorials",
  "best lip liners",
  "makeup contour palette",
  "highlighter shades for skin tones",
  "makeup for tanned skin",
  "bridal makeup brushes",
  "professional makeup kits",
  "airbrush makeup machines",
  "makeup for camera",
  "makeup for zoom calls",
  "minimal makeup looks",
  "bold eyebrow makeup",
  "eyeliner for beginners",
  "makeup for beginners",
  "full face makeup tutorials",
  "bridal makeup styles",
  "makeup for weddings",
  "makeup for photo shoots",
  "makeup for festivals",
  "nail art for summer",
  "nail art for winter",
  "nail art for weddings",
  "nail care at home",
  "nail strengthening treatments",
  "nail polish trends",
  "nail art techniques",
  "best nail colors for summer",
  "best nail colors for winter",
  "nail art for short nails",
  "nail art for long nails",
  "bridal nail art ideas",
  "holiday nail art",
  "festival nail designs",
  "gel nail art designs",
  "acrylic nail art designs",
  "simple nail art",
  "advanced nail art",
  "glitter nail polish",
  "matte nail polish",
  "nail art with rhinestones",
  "nail stamping art",
  "nail art tools",
  "nail art brushes",
  "nail art supplies",
  "nail art tutorial",
  "nail art ideas for beginners",
  "nail art designs for parties",
  "nail art for special occasions",
  "easy nail art designs"
];
