@BASE_URL = http://localhost:7000/users
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODczYzc5OTI5ZDZjMDc5M2JjMmY5M2EiLCJpYXQiOjE3NTMzMzg1MDN9.EYkBunhZhySYRPV8Ey2aG81L05ybsQ8OMJimCfkN5Ck

# LOGIN
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "email": "sujinasht307@gmail.com",
    "password": "sujina123"
}
###

# Register
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "name": "Sujina",
    "email": "sujinasht307@gmail.com",
    "password": "sujina123",
    "phone": "1234567890"  
}
###

# Reset User Password
POST {{BASE_URL}}/reset-code
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "sujinasht3071@gmail.com"
}

###

# Create New Password
POST {{BASE_URL}}/new-password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "" ,
    "resetCode": "123456",
    "newPassword": "sujina123" 
}

###


# Get User Profile
GET {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###


# Get User Metadata
GET {{BASE_URL}}/metadata
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###


# Update Search History
POST {{BASE_URL}}/search-history
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "searchTerm": "new makeup art designs"
}

###